{
    "InitialConfig_Std": {
        "ERROR": "module 'tests.generated_datasets.dataset_generator_numerical' has no attribute 'generate_numerical_step_data'",
        "traceback": "Traceback (most recent call last):\n  File \"/Users/kevinkoning/Library/CloudStorage/GoogleDrive-kevin.koning@gmail.com/My Drive/Code/NewBinomialTree/tests/test_accuracy.py\", line 303, in <module>\n    results_for_this_config = run_all_tests_for_config(config_params, verbose=verbose_output)\n  File \"/Users/kevinkoning/Library/CloudStorage/GoogleDrive-kevin.koning@gmail.com/My Drive/Code/NewBinomialTree/tests/test_accuracy.py\", line 151, in run_all_tests_for_config\n    \"generator_func\": dataset_generator_numerical.generate_numerical_step_data,\nAttributeError: module 'tests.generated_datasets.dataset_generator_numerical' has no attribute 'generate_numerical_step_data'\n"
    },
    "Config_Global_LeafPlus20": {
        "ERROR": "module 'tests.generated_datasets.dataset_generator_numerical' has no attribute 'generate_numerical_step_data'",
        "traceback": "Traceback (most recent call last):\n  File \"/Users/kevinkoning/Library/CloudStorage/GoogleDrive-kevin.koning@gmail.com/My Drive/Code/NewBinomialTree/tests/test_accuracy.py\", line 303, in <module>\n    results_for_this_config = run_all_tests_for_config(config_params, verbose=verbose_output)\n  File \"/Users/kevinkoning/Library/CloudStorage/GoogleDrive-kevin.koning@gmail.com/My Drive/Code/NewBinomialTree/tests/test_accuracy.py\", line 151, in run_all_tests_for_config\n    \"generator_func\": dataset_generator_numerical.generate_numerical_step_data,\nAttributeError: module 'tests.generated_datasets.dataset_generator_numerical' has no attribute 'generate_numerical_step_data'\n"
    },
    "Config_Global_LeafMinus5": {
        "ERROR": "module 'tests.generated_datasets.dataset_generator_numerical' has no attribute 'generate_numerical_step_data'",
        "traceback": "Traceback (most recent call last):\n  File \"/Users/kevinkoning/Library/CloudStorage/GoogleDrive-kevin.koning@gmail.com/My Drive/Code/NewBinomialTree/tests/test_accuracy.py\", line 303, in <module>\n    results_for_this_config = run_all_tests_for_config(config_params, verbose=verbose_output)\n  File \"/Users/kevinkoning/Library/CloudStorage/GoogleDrive-kevin.koning@gmail.com/My Drive/Code/NewBinomialTree/tests/test_accuracy.py\", line 151, in run_all_tests_for_config\n    \"generator_func\": dataset_generator_numerical.generate_numerical_step_data,\nAttributeError: module 'tests.generated_datasets.dataset_generator_numerical' has no attribute 'generate_numerical_step_data'\n"
    },
    "Config_Global_GainPlus1_0": {
        "ERROR": "module 'tests.generated_datasets.dataset_generator_numerical' has no attribute 'generate_numerical_step_data'",
        "traceback": "Traceback (most recent call last):\n  File \"/Users/kevinkoning/Library/CloudStorage/GoogleDrive-kevin.koning@gmail.com/My Drive/Code/NewBinomialTree/tests/test_accuracy.py\", line 303, in <module>\n    results_for_this_config = run_all_tests_for_config(config_params, verbose=verbose_output)\n  File \"/Users/kevinkoning/Library/CloudStorage/GoogleDrive-kevin.koning@gmail.com/My Drive/Code/NewBinomialTree/tests/test_accuracy.py\", line 151, in run_all_tests_for_config\n    \"generator_func\": dataset_generator_numerical.generate_numerical_step_data,\nAttributeError: module 'tests.generated_datasets.dataset_generator_numerical' has no attribute 'generate_numerical_step_data'\n"
    },
    "Config_Global_GainMinus0_01": {
        "ERROR": "module 'tests.generated_datasets.dataset_generator_numerical' has no attribute 'generate_numerical_step_data'",
        "traceback": "Traceback (most recent call last):\n  File \"/Users/kevinkoning/Library/CloudStorage/GoogleDrive-kevin.koning@gmail.com/My Drive/Code/NewBinomialTree/tests/test_accuracy.py\", line 303, in <module>\n    results_for_this_config = run_all_tests_for_config(config_params, verbose=verbose_output)\n  File \"/Users/kevinkoning/Library/CloudStorage/GoogleDrive-kevin.koning@gmail.com/My Drive/Code/NewBinomialTree/tests/test_accuracy.py\", line 151, in run_all_tests_for_config\n    \"generator_func\": dataset_generator_numerical.generate_numerical_step_data,\nAttributeError: module 'tests.generated_datasets.dataset_generator_numerical' has no attribute 'generate_numerical_step_data'\n"
    }
}