{
    "InitialConfig_Std": {
        "ERROR_MAIN_LOOP": "fit() got an unexpected keyword argument 'data'",
        "traceback": "Traceback (most recent call last):\n  File \"/Users/kevinkoning/Library/CloudStorage/GoogleDrive-kevin.koning@gmail.com/My Drive/Code/NewBinomialTree/tests/test_accuracy.py\", line 254, in <module>\n    results_for_this_config = run_all_tests_for_config(config_params, verbose=verbose_output)\n  File \"/Users/kevinkoning/Library/CloudStorage/GoogleDrive-kevin.koning@gmail.com/My Drive/Code/NewBinomialTree/tests/test_accuracy.py\", line 187, in run_all_tests_for_config\n    results_scenario = run_test_scenario(\n  File \"/Users/kevinkoning/Library/CloudStorage/GoogleDrive-kevin.koning@gmail.com/My Drive/Code/NewBinomialTree/tests/test_harness.py\", line 172, in run_test_scenario\n    tree.fit(\nTypeError: fit() got an unexpected keyword argument 'data'\n"
    },
    "Config_Global_LeafPlus20": {
        "ERROR_MAIN_LOOP": "fit() got an unexpected keyword argument 'data'",
        "traceback": "Traceback (most recent call last):\n  File \"/Users/kevinkoning/Library/CloudStorage/GoogleDrive-kevin.koning@gmail.com/My Drive/Code/NewBinomialTree/tests/test_accuracy.py\", line 254, in <module>\n    results_for_this_config = run_all_tests_for_config(config_params, verbose=verbose_output)\n  File \"/Users/kevinkoning/Library/CloudStorage/GoogleDrive-kevin.koning@gmail.com/My Drive/Code/NewBinomialTree/tests/test_accuracy.py\", line 187, in run_all_tests_for_config\n    results_scenario = run_test_scenario(\n  File \"/Users/kevinkoning/Library/CloudStorage/GoogleDrive-kevin.koning@gmail.com/My Drive/Code/NewBinomialTree/tests/test_harness.py\", line 172, in run_test_scenario\n    tree.fit(\nTypeError: fit() got an unexpected keyword argument 'data'\n"
    },
    "Config_MoreSplits": {
        "ERROR_MAIN_LOOP": "fit() got an unexpected keyword argument 'data'",
        "traceback": "Traceback (most recent call last):\n  File \"/Users/kevinkoning/Library/CloudStorage/GoogleDrive-kevin.koning@gmail.com/My Drive/Code/NewBinomialTree/tests/test_accuracy.py\", line 254, in <module>\n    results_for_this_config = run_all_tests_for_config(config_params, verbose=verbose_output)\n  File \"/Users/kevinkoning/Library/CloudStorage/GoogleDrive-kevin.koning@gmail.com/My Drive/Code/NewBinomialTree/tests/test_accuracy.py\", line 187, in run_all_tests_for_config\n    results_scenario = run_test_scenario(\n  File \"/Users/kevinkoning/Library/CloudStorage/GoogleDrive-kevin.koning@gmail.com/My Drive/Code/NewBinomialTree/tests/test_harness.py\", line 172, in run_test_scenario\n    tree.fit(\nTypeError: fit() got an unexpected keyword argument 'data'\n"
    }
}